/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import DB2_Conexion.Conexion_DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class AgregarModelo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarModelo.class.getName());

    public AgregarModelo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    // ========== MÉTODO PARA INSERTAR EN BASE DE DATOS ==========
    private boolean insertarModeloDB(String modelo, int capacidad, double peso) {
        Connection conn = null;
        PreparedStatement pstmt = null;
        
        try {
            // Usar tu Singleton de conexión
            conn = Conexion_DB.getInstance().getConnection();
            
            if (conn == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Error: No hay conexión a la base de datos",
                    "Error de conexión",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return false;
            }
            
            // Consulta SQL para insertar
            String sql = "INSERT INTO ModelosAvion (ModelNumber, Capacidad, Peso) VALUES (?, ?, ?)";
            pstmt = conn.prepareStatement(sql);
            
            // Asignar valores a los parámetros
            pstmt.setString(1, modelo.toUpperCase());  // Convertir a mayúsculas
            pstmt.setInt(2, capacidad);
            pstmt.setDouble(3, peso);
            
            // Ejecutar la inserción
            int resultado = pstmt.executeUpdate();
            
            return resultado > 0;
            
        } catch (SQLException e) {
            if (e.getErrorCode() == -803) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Ya existe un modelo con el número: " + modelo,
                    "Error de duplicado",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            } else if (e.getErrorCode() == -545) { // Violación de CHECK constraint
                javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Los datos no cumplen con las restricciones de validación",
                    "Error de validación DB2",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Error de base de datos: " + e.getMessage(),
                    "Error DB2",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            logger.severe("Error SQL: " + e.toString());
            return false;
            
        } finally {
            // Cerrar recursos
            try {
                if (pstmt != null) pstmt.close();
            } catch (SQLException e) {
                logger.warning("Error al cerrar PreparedStatement: " + e.toString());
            }
        }
    }
    
    private void vaciarCampos() {
        numModeloTxt.setText("");
        capacidadTxt.setText("");
        pesoTxt.setText("");
        numModeloTxt.requestFocus(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numModeloTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        capacidadTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pesoTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        agregarBtn = new javax.swing.JButton();
        vaciarBtn = new javax.swing.JButton();
        regresarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar Modelo");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero de modelo");

        numModeloTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numModeloTxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Capacidad");

        capacidadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacidadTxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Peso");

        pesoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(numModeloTxt)
                    .addComponent(capacidadTxt)
                    .addComponent(pesoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(numModeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(capacidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(pesoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        agregarBtn.setBackground(new java.awt.Color(0, 153, 0));
        agregarBtn.setForeground(new java.awt.Color(255, 255, 255));
        agregarBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\govan\\OneDrive\\Documentos\\1-Repositorio_Taller_BD\\Proyecto_Final_Taller_BD\\BD_Aeropuerto_Escritorio\\src\\main\\java\\Imagenes_Diseño\\icons8-agregar-24 (1).png")); // NOI18N
        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        vaciarBtn.setBackground(new java.awt.Color(0, 153, 153));
        vaciarBtn.setForeground(new java.awt.Color(0, 0, 0));
        vaciarBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\govan\\OneDrive\\Documentos\\1-Repositorio_Taller_BD\\Proyecto_Final_Taller_BD\\BD_Aeropuerto_Escritorio\\src\\main\\java\\Imagenes_Diseño\\icons8-limpiar-24.png")); // NOI18N
        vaciarBtn.setText("Vaciar");
        vaciarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciarBtnActionPerformed(evt);
            }
        });

        regresarBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\govan\\OneDrive\\Documentos\\1-Repositorio_Taller_BD\\Proyecto_Final_Taller_BD\\BD_Aeropuerto_Escritorio\\src\\main\\java\\Imagenes_Diseño\\icons8-volver-24.png")); // NOI18N
        regresarBtn.setText("Regresar");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regresarBtn)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(agregarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vaciarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(agregarBtn)
                .addGap(40, 40, 40)
                .addComponent(vaciarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regresarBtn)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        // TODO add your handling code here:
        MenuModelos menu = new MenuModelos();   // crear ventana principal
       
    menu.setVisible(true);                // mostrar

    this.dispose();
    }//GEN-LAST:event_regresarBtnActionPerformed

    
    
    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        // TODO add your handling code here:
         try {
            
            String numeroModelo = numModeloTxt.getText().trim();
            String capacidadText = capacidadTxt.getText().trim();
            String pesoText = pesoTxt.getText().trim();
            
            
            if (numeroModelo.isEmpty() || capacidadText.isEmpty() || pesoText.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Todos los campos son requeridos",
                    "Error de validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            
            if (numeroModelo.length() < 2) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Número de modelo debe tener al menos 2 caracteres",
                    "Error de validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            if (!numeroModelo.matches("^[A-Za-z0-9-]+$")) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Número de modelo solo puede contener letras, números y guiones",
                    "Error de validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int capacidad;
            try {
                capacidad = Integer.parseInt(capacidadText);
                if (capacidad < 1 || capacidad > 1000) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "❌ Capacidad debe estar entre 1 y 1000",
                        "Error de validación",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Capacidad debe ser un número entero válido",
                    "Error de validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            double peso;
            try {
                peso = Double.parseDouble(pesoText);
                if (peso < 500 || peso > 1000000) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "❌ Peso debe estar entre 500 y 1,000,000",
                        "Error de validación",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Peso debe ser un número decimal válido",
                    "Error de validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            boolean exito = insertarModeloDB(numeroModelo, capacidad, peso);
            
            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "✅ Modelo de avión agregado exitosamente",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                vaciarCampos();
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "❌ Error inesperado: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            logger.severe("Error al agregar modelo: " + e.toString());
        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void vaciarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciarBtnActionPerformed
        // TODO add your handling code here:
        vaciarCampos();
    }//GEN-LAST:event_vaciarBtnActionPerformed

    private void numModeloTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numModeloTxtActionPerformed
        // TODO add your handling code here:
        capacidadTxt.requestFocus();
    }//GEN-LAST:event_numModeloTxtActionPerformed

    private void capacidadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacidadTxtActionPerformed
        // TODO add your handling code here:
         pesoTxt.requestFocus();
    }//GEN-LAST:event_capacidadTxtActionPerformed

    private void pesoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoTxtActionPerformed
        // TODO add your handling code here:
         //agregarBtn.requestFocus();
         // Ejecutar el botón Agregar en un hilo separado
    new Thread(() -> {
        javax.swing.SwingUtilities.invokeLater(() -> {
            agregarBtnActionPerformed(evt);
        });
    }).start();
         
         
         
    }//GEN-LAST:event_pesoTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AgregarModelo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JTextField capacidadTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField numModeloTxt;
    private javax.swing.JTextField pesoTxt;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JButton vaciarBtn;
    // End of variables declaration//GEN-END:variables
}
