/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import DB2_Conexion.Conexion_DB;
import java.sql.Connection;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class TransaccionModelos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransaccionModelos.class.getName());
    private String modeloActual = "";
    private int capacidadActual = 0;
    private double pesoActual = 0.0;

    public TransaccionModelos() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Transacción - Cambio de Capacidad");
        
        txtCapacidadNueva.setEnabled(false);
        txtCapacidadNueva.setText("");
        jTextArea1.setText("Ingresa número de modelo y presiona Buscar");
    }
    
   
    
    private void manejarErrorSQL(SQLException e) {
        String error = e.getMessage();
        
        if (error.contains("Capacidad inválida")) {
            JOptionPane.showMessageDialog(this, "Error: Capacidad fuera de rango (1-1000)");
        } else if (error.contains("no existe")) {
            JOptionPane.showMessageDialog(this, "Error: Modelo no encontrado");
        } else {
            JOptionPane.showMessageDialog(this, "Error SQL: " + error);
        }
        
        jTextArea1.setText("TRANSACCIÓN FALLIDA\nError: " + error);
        resetearDatos();
    }
    
    private void resetearDatos() {
        modeloActual = "";
        capacidadActual = 0;
        pesoActual = 0.0;
        txtCapacidadNueva.setEnabled(false);
        txtCapacidadNueva.setText("");
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarNumeroModelo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnEjecutar = new javax.swing.JButton();
        txtCapacidadNueva = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transaccion Modelo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Actualizacion de capacidad");

        txtBuscarNumeroModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarNumeroModeloActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        txtCapacidadNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadNuevaActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingresar capacidad nueva");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(txtBuscarNumeroModelo))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addContainerGap(45, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtCapacidadNueva)
                                        .addGap(49, 49, 49))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEjecutar)
                                .addGap(75, 75, 75))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarNumeroModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCapacidadNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBuscar))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnEjecutar)))
                .addGap(12, 12, 12)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarNumeroModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarNumeroModeloActionPerformed
        // TODO add your handling code here:
         btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_txtBuscarNumeroModeloActionPerformed

    private void txtCapacidadNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadNuevaActionPerformed
        // TODO add your handling code here:
        btnEjecutarActionPerformed(evt);

    }//GEN-LAST:event_txtCapacidadNuevaActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        // TODO add your handling code here:
        if (modeloActual.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero busca un modelo");
            return;
        }
        
        String capacidadText = txtCapacidadNueva.getText().trim();
        
        if (capacidadText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa la nueva capacidad");
            txtCapacidadNueva.requestFocus();
            return;
        }
        
        try {
            int nuevaCapacidad = Integer.parseInt(capacidadText);
            
            if (nuevaCapacidad < 1 || nuevaCapacidad > 1000) {
                JOptionPane.showMessageDialog(this, "Capacidad debe ser 1-1000");
                txtCapacidadNueva.requestFocus();
                return;
            }
            
            int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Cambiar capacidad de " + modeloActual + "?\n" +
                "De " + capacidadActual + " a " + nuevaCapacidad,
                "Confirmar",
                JOptionPane.YES_NO_OPTION);
            
            if (respuesta != JOptionPane.YES_OPTION) {
                return;
            }
            
            Connection conn = Conexion_DB.getInstance().getConnection();
            CallableStatement stmt = null;
            ResultSet rs = null;
            
            try {
                String sql = "{call SP_CAMBIO_CAPACIDAD(?, ?)}";
                stmt = conn.prepareCall(sql);
                stmt.setString(1, modeloActual);
                stmt.setInt(2, nuevaCapacidad);
                
                rs = stmt.executeQuery();
                
                if (rs.next()) {
                    String modelo = rs.getString("MODELO");
                    int antes = rs.getInt("ANTES");
                    int despues = rs.getInt("DESPUES");
                    double peso = rs.getDouble("PESO");
                    double densidad = rs.getDouble("KG_POR_PASAJERO");
                    
                    jTextArea1.setText(
                        "TRANSACCIÓN EXITOSA\n" +
                        "Modelo: " + modelo + "\n" +
                        "Capacidad anterior: " + antes + "\n" +
                        "Capacidad nueva: " + despues + "\n" +
                        "Peso: " + peso + "\n" +
                        "Densidad: " + String.format("%.2f", densidad) + " kg/pax"
                    );
                    
                    capacidadActual = despues;
                    
                    JOptionPane.showMessageDialog(this, "Cambio realizado exitosamente");
                    
                    txtCapacidadNueva.setText("");
                    txtCapacidadNueva.requestFocus();
                    
                } else {
                    JOptionPane.showMessageDialog(this, "No se obtuvieron resultados");
                }
                
            } catch (SQLException e) {
                manejarErrorSQL(e);
            } finally {
                try { if (rs != null) rs.close(); } catch (Exception e) {}
                try { if (stmt != null) stmt.close(); } catch (Exception e) {}
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La capacidad debe ser un número");
            txtCapacidadNueva.requestFocus();
        }
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
         String modelo = txtBuscarNumeroModelo.getText().trim();
        
        if (modelo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa número de modelo");
            txtBuscarNumeroModelo.requestFocus();
            return;
        }
        
        Connection conn = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;
        
        try {
            conn = Conexion_DB.getInstance().getConnection();
            
            String sql = "SELECT ModelNumber, Capacidad, Peso FROM ModelosAvion WHERE ModelNumber = ?";
            stmt = conn.prepareStatement(sql);
            stmt.setString(1, modelo);
            rs = stmt.executeQuery();
            
            if (rs.next()) {
                modeloActual = rs.getString("ModelNumber");
                capacidadActual = rs.getInt("Capacidad");
                pesoActual = rs.getDouble("Peso");
                
                jTextArea1.setText(
                    "Modelo: " + modeloActual + "\n" +
                    "Capacidad actual: " + capacidadActual + "\n" +
                    "Peso: " + pesoActual + "\n\n" +
                    "Ingresa nueva capacidad:"
                );
                
                txtCapacidadNueva.setEnabled(true);
                txtCapacidadNueva.requestFocus();
                txtCapacidadNueva.setText("");
                
            } else {
                jTextArea1.setText("Modelo no encontrado: " + modelo);
                resetearDatos();
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            resetearDatos();
        } finally {
            try { if (rs != null) rs.close(); } catch (Exception e) {}
            try { if (stmt != null) stmt.close(); } catch (Exception e) {}
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
         MenuModelos menu = new MenuModelos();   
       
    menu.setVisible(true);                

    this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtBuscarNumeroModelo;
    private javax.swing.JTextField txtCapacidadNueva;
    // End of variables declaration//GEN-END:variables
}
